import=["~/.config/alacritty/alacritty_tanim.toml"]

[shell]
  program = "/usr/local/bin/fish"
  args= ["-l", "-c", "zellij attach --index 0 || zellij"]
    
[window]
decorations = "Buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 2
y = 2

[font]
size = 14.0

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
