theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
auto-save = true
bufferline = "multiple"
true-color = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
C-s = ":w" # Kaydetmet için
C-o = ":open"
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0 = ["goto_line_start"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
